### ISSUE TITLE
how to use argument.autoMockableTestableImports and argument.autoMockableImports ??

### ISSUE THREAD

**Issue by alexvbush** [krzysztofzablocki/Sourcery#1024]
hi, I'm trying to have my project main target be and other dependencies be automatically imported into my auto generated mocks file. I see that the default template has `autoMockableTestableImports` and `autoMockableImports` argument params in it but I can't figure out how to use it?

**Comment by krzysztofzablocki** [comment]
you pass them in your sourcery configuration file as arguments, [example configs are in docs](http://merowing.info/Sourcery/usage.html)

**Comment by alexvbush** [comment]
thank you @krzysztofzablocki 

I created the following config but it doesn't seem to work:

```yml
sources:
  - ../MyiOSTarget
templates:
  - ../Pods/Sourcery/Templates/AutoMockable.stencil
output:
  ../MyiOSTargetTests/AutoGeneratedMocks.swift
args:
  autoMockableTestableImports: MyiOSTarget
  autoMockableImports: MyLibraryTarget
```

**Comment by Nikoloutsos** [comment]
@alexvbush 
FYI at any given moment write the following in the stencil file to get what the arguments have (good for debugging)
```stencil
{{argument]]
```
So if you do that you will realise your arguments are there. But why they are not playing correctly?
That's because if you take a closer look to the implementation of autoMock.stencil **a for loop is used**.

And for loop works only for arrays. So nothing happens for your single values `MyiOSTarget` and `MyLibraryTarget`.

In order to make it work you have to do the following:

```yml
sources:
  - ../MyiOSTarget
templates:
  - ../Pods/Sourcery/Templates/AutoMockable.stencil
output:
  ../MyiOSTargetTests/AutoGeneratedMocks.swift
args:
  autoMockableTestableImports: ["MyiOSTarget"]
  autoMockableImports: ["MyLibraryTarget"]
```
