### ISSUE TITLE
Generating mocks for protocols exposed from a Swift Package

### ISSUE THREAD

**Issue by Velin92** [krzysztofzablocki/Sourcery#1152]
Hello!

I would like to generate mocks for a protocols that are not in my codebase, but are exposed from the codebase of a Swift Package.

How may I be able to generate those mocks for such protocols in my codebase?
Since I am not able to extend a protocol with AutoMockable or // sourcery: AutoMockable, and since also they do not belong directly in my codebase and not get scanned.

**Comment by Velin92** [comment]
Hello no news on this so far?

**Comment by krzysztofzablocki** [comment]
You need to get at least definition scanned, you can add conformance in your own project code

**Comment by Velin92** [comment]
> You need to get at least definition scanned, you can add conformance in your own project code

How may I achieve this?
Since the it's an SPM the definition is not really in project, how can I set the .yml configuration to scan the SPM package code?

**Comment by krzysztofzablocki** [comment]
You'd need to use the [spm cache](https://developer.apple.com/forums/thread/673976)

**Comment by Velin92** [comment]
> You'd need to use the [spm cache](https://developer.apple.com/forums/thread/673976)

I tried to use the swiftpm cache in the config file like this:

```
sources:
  - ../../ElementX
  - ~/Library/Caches/org.swift.swiftpm/
templates:
  - AutoMockable.stencil
output:
  ../../ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
args:
  automMockableTestableImports: []
  autoMockableImports: [Combine, Foundation, MatrixRustSDK, AnalyticsEvents]
```

However it's still trying to access my folder locally instead of accessing it from the user folde, in fact the script fails saying:
'/Users/mauroromito/Documents/Xworkspace/element-x-ios/Tools/Sourcery/Library/Caches/org.swift.swiftpm' does not exist or is not readable.

Of course since the sourcery script should also work across multiple collaborators and on the CI, I can't use multiple ../ to reach the user folder.

How would I achieve that with the .yml configuration?
