### ISSUE TITLE
Sourcery does not see files during generation and linking to the project

### ISSUE THREAD

**Issue by red-beeard** [krzysztofzablocki/Sourcery#1157]
Hi, I tried to do it myself, and also looked for tutorials for the link key in the yaml. When I use it, I get an error when generating it. 

I used this [article](https://engineering.theblueground.com/how-we-saved-our-time-with-sourcery-in-ios/). Here is the [repository](https://github.com/bluegroundltd/ios_sourcery_demo?ref=engineering.theblueground.com) on which this is reproduced.

```shell
red_beeard@MacBook-Pro-Alex ios_sourcery_demo-main % sourcery
Using configuration file at '.sourcery.yml'
Scanning sources...
Found 10 types in 5 files, 5 changed from last run.
Files changed:
/Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp/Calculator.swift
/Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp/FooAppApp.swift
/Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp/Macbook.swift
/Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp/ContentView.swift
/Users/red_beeard/Downloads/ios_sourcery_demo-main/Sourcery/FixturableCommonExamples.swift
Loading templates...
Loaded 2 templates.
Generating code...
warning: Failed to link file at /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooAppTests/Sourcery/AutoFixturable.generated.swift to /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp.xcodeproj. The file at path /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooAppTests/Sourcery/AutoFixturable.generated.swift doesn't exist
warning: Failed to link file at /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooAppTests/Sourcery/AutoMockable.generated.swift to /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooApp.xcodeproj. The file at path /Users/red_beeard/Downloads/ios_sourcery_demo-main/FooAppTests/Sourcery/AutoMockable.generated.swift doesn't exist
Finished.
Processing time 0.10806906223297119 seconds
```

Configuration:
```yaml
# READ MORE ABOUT configuration here https://merowing.info/Sourcery/usage.html
configurations:
    # -- Blueground configuration --
    - sources:
        include:
          - FooApp
          - Sourcery # We need to read the FixturableCommonExamples.swift
      templates:
        - Sourcery
      output:
          path: FooAppTests/Sourcery
          link:
            project: ./FooApp.xcodeproj
            target: FooAppTests
            group: FooAppTests/Sourcery
      args:
        testableImport: "FooApp" # [MANDATORY] Your mocks will have "@testable import <testableImport>"
        containedPathSubstringToApplyTemplate: "/FooApp/" # [MANDATORY] If a protocol with Automockable annotation exists but it's path doesn't contain <focusFolder> it will be ignored.

```
