### ISSUE TITLE
XCLocalSwiftPackageReference is not supported

### ISSUE THREAD

**Issue by ProudOfZiggy** [krzysztofzablocki/Sourcery#1206]
Hi!

After updating to Xcode 15 I have next error with my yml file:

```
Using configuration file at '../.sourcery-share-extension.yml' error: while reading .yml../.sourcery-share-extension.yml'.
The element XCLocalSwiftPackageReference is not supported
```

My yml file:

```
project:
  file: MyApp.xcodeproj
  target:
    name: "MyAppSharingExtension"
  exclude:
    - Packages
templates:
  - MyAppTemplate.stencil
output:
  Result.swift
```

If I use `sources` instead of `project` I got no error, but I need to use `project` to gather classes that added in a specific target.

P.S. Project has a lot of connected Swift packages.
