### ISSUE TITLE
Xcode 15 - Failed to parse target info (malformed)

### ISSUE THREAD

**Issue by joseneves-neon** [krzysztofzablocki/Sourcery#1217]
After update to Xcode 15 I start to see this error when running sourcery

command to run `${SRCROOT}/Pods/Sourcery/bin/sourcery --config "$path" --buildPath ${SRCROOT}/temp/${array[6]} --prune`

```
error: InternalError(description: "Internal error. Please file a bug at https://github.com/apple/swift-package-manager/issues with this info. Failed to parse target info (malformed).\nRaw compiler output: ")
Using configuration file at '/Users/***/Meta/Configuration/Sourcery.yml'
Scanning sources...
Found 0 types in 0 files, 0 changed from last run.
Loading templates...
Loaded 2 templates.
```

**Comment by art-divin** [comment]
Hello @joseneves-neon 👋🏻 ,

Thank you very much for reporting the issue 👍🏻 

Could you please share the configuration (`.yml`) file used for Sourcery invocation? You can omit internal details, I just wonder if there is something unusual there.

Thanks 🤝

**Comment by joseneves-neon** [comment]
sure!
```
sources:
    include:
        - ./../../<FeatureModuleName>API/Models
        - ./../../<FeatureModuleName>API/Web Services
    exclude:
        - ./../../<FeatureModuleName>APITestsHelper

templates:
    - ../../../../../Libraries/Meta/NeonSourcery/NeonSourcery/Templates/ModelsMock/ModelsMock.swifttemplate
    - ../../../../../Libraries/Meta/NeonSourcery/NeonSourcery/Templates/WebServicesMock/WebServicesMock.swifttemplate

output:
    ./../../<FeatureModuleName>APITestsHelper

args:
    projectName: NeonRecoveryPasswordAPI
```
