### ISSUE TITLE
Cli command option --args seems not working.

### ISSUE THREAD

**Issue by lukaszspaczynski** [krzysztofzablocki/Sourcery#1233]
Passing args through the command line seems not working. 

Command:
`sourcery --config .sourcery.yml --args arg1=val1`

Config:
```
configurations:
  - sources:
      - "./"
    templates:
      - "./template.stencil"
    output:
      "./gen.swift"
```

Template:
`{{argument.arg1}}`

Result:
arg1 in template is not present.
