### ISSUE TITLE
Annotations not parse when running Sourcery with the same template but different output files

### ISSUE THREAD

**Issue by alexdmotoc** [krzysztofzablocki/Sourcery#1357]
Hi!

I have a setup where I have one `AutoMockable.stencil` file that I use as template for 2 configurations. One configuration outputs in a file in the unit tests target, and one in the App target.

I use this to generate mocks for SwiftUI previews and also have them for unit tests.

Another note is, I use 2 `// sourcery: AutoMockable` annotations:
- the standard `// sourcery: AutoMockable` - used to output in the tests target file
- a new `// sourcery: AutoMockableApp` - used to output in the App target file

I also have some custom flags configured in the `.sourcery.yml` to be able to differentiate which configuration is run (the unit tests or app) in order to customize the resulting mocks.

Finally, the super-weird part is that some times it works, but if I run `sourcery` multiple times consecutively, it breaks and doesn't find the annotations in one of the configurations

My `.sourcery.yml` looks like this

```yml
configurations:
  - sources: 
      - Sources/
    templates:
      - /Stencils/AutoMockable.stencil
    output: Tests/Mocks/GeneratedMocks.swift
    args:
      isTestTargetMocks: true
      autoMockableImports: [
        "Combine",
      ]
      autoMockableTestableImports: [
        "MyApp"
      ]
  - sources: 
      - Sources/
    templates:
      - /Stencils/AutoMockable.stencil
    output: MyApp/Core/Generators/GeneratedBuilders.swift
    args:
      isAppTargetMocks: true
      autoMockableImports: [
        "Combine",
      ]
```

The `AutoMockable.stencil` is the same like the template one on this repo, just modified it a bit to not generate CalledCount, etc for the App target mocks.

Mocked protocol looks like this

```swift
// sourcery: AutoMockable
// sourcery: AutoMockableApp
protocol ArticlePagedLoaderType: ObservableObject {
    var articles: [Article] { get }
    var isLoading: Bool { get }
}
```

Attached photos of the output in the App target

Any ideas what could be the problem?

![Screenshot 2024-08-10 at 21 39 13](https://github.com/user-attachments/assets/bd873983-8bf5-4d29-9181-74e61425d715)
![Screenshot 2024-08-10 at 21 39 33](https://github.com/user-attachments/assets/cb925664-7e82-4e31-a5b9-14b1fdec26b3)
