### ISSUE TITLE
Sourcery ignores output folder

### ISSUE THREAD

**Issue by milch** [krzysztofzablocki/Sourcery#375]
Hi,

For some reason, Sourcery seems to ignore my output folder completely. I've tried multiple ways of setting it: 

- `.sourcery.yml`:
```yml
--- 
output: 
  - Project/Generated/
sources: 
  - Project/
templates: 
  - Project/Templates/
```
- CLI: `Pods/Sourcery/bin/sourcery --output ./Project/Generated`

Sourcery always puts my generated files into the root project folder. Everything else is picked up with no problem, it's just the output path that's wrong. 

I'm using version 0.7.2 with swift templates, if that helps. Let me know if you need anything else.

**Comment by Antondomashnev** [comment]
Hi @milch I've tried to reproduce the issues you reported. To do so I created a sample [project](https://github.com/Antondomashnev/SourceryGeneratedCodeFolderIssue) with `swifttemplate`.
I integrated Sourcery and run it as a `RunScriptPhase`. After all, it's working fine. 

May I ask you if this folder exists `Project/Generated/` in your project? Sourcery doesn't generate folder, if there is no one, the file will be stored in the root directory.

**Comment by milch** [comment]
Hmm, I tried checking out your project to see if it would change anything, and to my surprise it seems to be working there! I've isolated the issue to be related to the `.sourcery.yml` file. If you drop the following file into your test project, the generated file will always be in the root irrespective of the parameters that you pass - even if the folder exists:

```yml
--- 
output: 
  - Generated/
sources: 
  - SourceryTest/
templates: 
  - Templates/
```
