### ISSUE TITLE
`exclude` does not work when using `project` in config file

### ISSUE THREAD

**Issue by haimwaking** [krzysztofzablocki/Sourcery#419]
#Hi,

I have this configuration
```yml
project:
  file: Project.xcodeproj
  root: .
  target:
    name: Project
  exclude:
    - Project/Classes/Generated
```

Sourcery fails to run because it tries to find files under `Project/Classes/Generated` which have not yet been created.
