### ISSUE TITLE
Templates documentation api

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#531]
Annotations are not compiled and very easy to type wrong. Then it can produce confusing result for which requires to read template carefully. To improve understanding of templates we can introduce documentation api that can be used in header comment of template and can look like this:

```
{#
desc: description of template
annotations:
  some_annotation: description of annotation
  another_annotation: description of annotation
#}
```

Then we can parse annotations from in these comments and when we parsing them from code and find unknown annotation we can suggest user with correct syntax using the same approach as in #471.
We can do the same for arguments, though they are less used and only passed once when running tool.
