### ISSUE TITLE
Getting error "Unknown type AutoEquatable, should be used with `based`"

### ISSUE THREAD

**Issue by SpacyRicochet** [krzysztofzablocki/Sourcery#562]
I'm trying out Sourcery on a hobby project and am encountering issues while trying to generate the code. It errors with the following message:

```
Using configuration file at '.sourcery.yml'. WARNING: Ignoring the parameters passed in the command line.
Scanning sources...
Found 4 types.
Loading templates...
Loaded 7 templates.
Generating code...
error: Unknown type AutoCases, should be used with `based`
error: Unknown type AutoEquatable, should be used with `based`
error: Unknown type AutoEquatable, should be used with `based`
error: Unknown type AutoHashable, should be used with `based`
error: Unknown type AutoHashable, should be used with `based`
error: Unknown type AutoLenses, should be used with `based`
Processing time 0.164284110069275 seconds
```

---

I've performed the following steps;

1. Install via CocoaPods.

2. Add 'Run Script' build phase to run `sourcery` from the Pods directory.
```
"$PODS_ROOT/Sourcery/bin/sourcery"
```

3. Create a `.sourcery.yml` file for configuration.

```
sources:
  - LevelCounter/Model
templates:
  - Pods/Sourcery/Templates
output:
  Sourcery.generated.swift
```

4. Add a file to define the `AutoEquatable` protocol.

```
protocol AutoEquatable  {}
```

5. Make my model conform to `AutoEquatable`.

```
import Foundation

class Person: Codable {
    let identifier: UUID
    var name: String

    init(identifier: UUID? = nil, name: String) {
        self.identifier = identifier ?? UUID()
        self.name = name
    }
}

extension Person: AutoEquatable {}
```

---

Anyone know what I'm doing wrong?

**Comment by ilyapuchka** [comment]
Source file that defines AutoEquatable is not scanned by Sourcery, you should put it in Models folder or provide a path to it in config file. And the rest of templates you don't need, so exlude them to avoid those errors.

**Comment by SpacyRicochet** [comment]
That works! Thanks :)

**Comment by Lascorbe** [comment]
For anyone coming here, I got this issue and I fixed it (thanks to @ilyapuchka!), but I saw something weird: 

My `.sourcery.yml` looked like this (this is the file that caused this error):

```
configurations:
    # CloudFeature
    - sources:
        include:
            - ios/Packages/Sources/CloudFeature/
      templates:
          - ios/SourceryTemplates/
      output: ios/Packages/Sources/CloudFeature/Sourcery/
      baseIndentation: 4
      args:
        autoMockableImports:
          - SharedModels
        autoMockableTestableImports:
```

then I changed the sources to:

```
    - sources:
        include:
            - ios/Packages/Sources/
```

It worked! But I tried again the previous path because, why not? I mean the `templates` path isn't even on the sources path so why `ios/Packages/Sources/CloudFeature/` didn't work but `ios/Packages/Sources/` did?

Now it also works with the first path I had for sources in the first place 🤔 (`ios/Packages/Sources/CloudFeature/`). Is this expected?

(BTW, I'm using Sourcery as a pre-commit hook, v2.1.7)
