### ISSUE TITLE
Using several project or target objects in config does not work

### ISSUE THREAD

**Issue by rubensamsonyanauto1** [krzysztofzablocki/Sourcery#717]
The problem came from the need to have a module name. In the sources, I saw there is a `module` in `Type`, which is not specified in docs. Also, there is a `globalName` variable, which seems to be what I need, but it's internal and uses the module to compose its value. If I use `sources` for scanning files, the `module` is always nil. To have the correct value of `module` I need to use `project` in configuration. But now I have another issue. In docs written `You can use several project or target objects to scan multiple targets from one project or to scan multiple projects`, but in fact it only scans the last defined target. I have tried several configurations, like:
```
project:
  file: test.xcodeproj
  target:
    name: test
templates:
  - Templates
output:
  path: CodeGenerated
project:
  file: Pods/Pods.xcodeproj
  target:
    name: SomeFramework
templates:
  - Templates
output:
  path: CodeGenerated
```

Also 

```
project:
  file: test.xcodeproj
  target:
    name: test
project:
  file: Pods/Pods.xcodeproj
  target:
    name: SomeFramework
templates:
  - Templates
output:
  path: CodeGenerated
```

**Comment by ilyapuchka** [comment]
In YAML arrays of objects are defined like this:

```yaml
project:
  - file: test1.xcodeproj
    target:
      name: test
  - file: test2.xcodeproj
    target:
      name: test2
```

https://stackoverflow.com/questions/33989612/yaml-equivalent-of-array-of-objects-in-json
