### ISSUE TITLE
multiple configurations in .sourcery.yml

### ISSUE THREAD

**Issue by ottosuess** [krzysztofzablocki/Sourcery#727]
I want to apply several templates just to one specific folder each.

Is there an option to have multiple configurations in the .sourcery.yml file?
I think something like this would be nice:

```
configurations:
  - sources:  Library/Model/
    templates: Sourcery/a.stencil
    output: Library/Generated
  - sources: Main/Model/
    templates:  Sourcery/b.stencil
    output: Main/Generated
```
