### ISSUE TITLE
When I declare multiple targets it only processes one

### ISSUE THREAD

**Issue by tahirmt** [krzysztofzablocki/Sourcery#819]
When I specify a project and multiple `target`s to read multiple modules at once I only see types from the last module and not the rest.

Here is what my `.sourcery.yml` file looks like
```
project:
  file: Sources/Sample.xcodeproj
  target:
    name: Sample
    module: Sample
  target:
    name: Module1
    module: Module1
  target:
    name: Module2
    module: Module2
templates:
  - Templates
output:
  Sources/Generated
```

And a template

```
{% for structType in types.structs %}
// module is {{structType.module}} for {{structType.name}}
{% endfor %}
```

It only prints the module names of the `Module2`
