### ISSUE TITLE
Adding extra blank lines after header

### ISSUE THREAD

**Issue by acecilia** [krzysztofzablocki/Sourcery#829]
Hi:

With versions `0.17.0` and `0.18.0` I am experiencing a weird issue: I am getting an extra blank line after the header:

```swift
// Generated using Sourcery 0.18.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

                      <=== Extra blank line that raises a warning when using swiftlint
// swiftlint:disable all
...
```

I am running Xcode 10.3.1 and MacOS Catalina 10.15.4.

My `.sourcery.yml` file is similar to the one below:
```yaml
sources:
 - Something
templates:
  - ../../../Something/Templates
output:
  SomethingTests/Mocks/AutoMockable.swift
```

I have been looking into it, but I did not get to any solution. It happens independently of the content of the template.

Thanks
