### ISSUE TITLE
Automatically resolve types across modules

### ISSUE THREAD

**Issue by krishnaagarwal1994** [krzysztofzablocki/Sourcery#899]
I am parsing a method in a class A present in TargetA, 
Class A has a method that has a return type of Class B, which is also present in TargetA.
But sourcery is still returning false for 
```
{{ method.returnType }} -> nil
{{ method.returnTypeName }} -> ClassB

```
The configuration file that I am using

```
project:
  - file: #path to project file
    target:
      name: TargetA
templates:
    - SourceryTemplates
output: src/Generated
```
