### ISSUE TITLE
Lots of warnings 'Found "extension <Type>" of type for which there is no original type declaration information' with v1.2.0

### ISSUE THREAD

**Issue by Lutzifer** [krzysztofzablocki/Sourcery#903]
Since Version 1.2.0 I have a lot of warnings like:

`Found "extension Dictionary" of type for which there is no original type declaration information`

This happens to Foundation classes (Dictionary, Collections, UnitDuration, Measurement, FileManager), classes from Pods (RxSwift.Observable) and classes defined in the current app.

Config file:

```
project:
  file: ../../${N42_PROJECT_NAME}.xcodeproj
  target:
    name: ${N42_PRODUCT_NAME}
templates:
  - SourceryTemplates/
output: ../../Sources/App/Release/Sourcery
args:
  additionalImports: |
    import ${N42_KIT_NAME}
```

Maybe related to https://github.com/krzysztofzablocki/Sourcery/issues/887 ?
