### ISSUE TITLE
configuration: Linking to different path from output path

### ISSUE THREAD

**Issue by mlight3** [krzysztofzablocki/Sourcery#904]
My recent project's group hierarchy is not the same as actual folders.
When I try to link my generated files to target, it created different folders and got errors.

### Configuration
```yml
sources:
  - mytype/Sources
templates:
  - mytype/Sources/Sourcery/Templates
output:
  path: ./mytype/Sources/Sourcery/Generated
  link:
    project: mytype.xcodeproj
    target: mytype
    group: mytype/Sources/Sourcery/Generated
```

### Group Hierarchy
* mytype (Root Group)
  * Sourcery
      * Sourcery
        * Generated

### Folder Hierarchy
* mytype
  * Sources
    * Sourcery
      * Generated

**`mytype` group location is `mytype/Soucres'**

### Problem
Sourcery generates a new group even if the root group is the same as the first group in the configuration group path. The first group from `mytype/Sources/Sourcery/Generated` is the same as root group: `mytype`. But sourcery creates new group. 

Sourcery cannot handle if the group's location is not the same as the folder.
My root group is `mytype`, but folder location is `mytype/Sources`.
