### ISSUE TITLE
configuration: "force-parse" option issue

### ISSUE THREAD

**Issue by Roman-Andreyenko** [krzysztofzablocki/Sourcery#937]
I found issue when I used configuration file. If I use "project" option as source of source code, then "force-parse" option does not work for multiple phases generation. In case if I use "sources" option as source of source code, "force-parse" does well.

Configuration file:
```
project:
   file: ../Recipes.xcodeproj
   target:
      - name: Recipes
      - name: FractalTookit
templates:
   - ./templates
force-parse:
   - generated
output:
   ../Recipes/generated
```

I did following:
1. run sourcery with configuration file described above
2. sourcery generates several source code files
3. I added them to the Recipes target manually
4. run sourcery again, but it does not scan generated classes

In case if I use following configuration file, sourcery scans generated files on the second generation phase:
```
sources:
   - ../Recipes
   - ../FractalTookit
templates:
   - ./templates
force-parse:
   - generated
output:
   ../Recipes/generated
```

Seems that this is issue. Or maybe I do something wrong?

My machine:
macOS Catalina 10.15.7
Xcode 12.4
swift 5.3.2
sourcery 1.3.4
